#
## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------
servicecomb:
  tracing:
    enabled: true # 是否启用调用链追踪功能，默认为 true
  service:
    application: scb-fence
    name: edge-service
    version: 0.0.1

  registry:
    zk:
      enabled: true
      connectString: ${ZK_SERVER:127.0.0.1:2181}
  config:
    zk:
      enabled: true
      connectString: ${ZK_SERVER:127.0.0.1:2181}

  rest:
    address: 0.0.0.0:${APP_PORT:9090}

  matchGroup:
    allOperation: |
      matches:
       - apiPath:
           prefix: "/"
  rateLimiting:
    ## 限流器每10毫秒允许通过100个请求，如果一个请求超过1000毫秒没有获取到
    ## 许可，将被拒绝
    allOperation: |
      rate: 100
      limitRefreshPeriod: 10
      timeoutDuration: 1000
  retry:
    ## 熔断或者实例不可用等场景重试一次
    allOperation: |
      maxAttempts: 2
      retryOnSame: 0
      retryOnResponseStatus: 
         - 502
         - 503
      waitDuration: 1
  instanceIsolation:
    ## 熔断器错误率达到50%或者耗时请求达到100%，将开启。
    ## 开启时间为5000毫秒，然后会放通10个请求。
    allOperation: |
      minimumNumberOfCalls: 10
      slidingWindowSize: 20
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 1000
      waitDurationInOpenState: 5000
      permittedNumberOfCallsInHalfOpenState: 10
  instanceBulkhead:
    ## 隔离仓限制正在处理的请求数为20个，新来的请求等待1000毫秒没有获取到
    ## 许可，将被拒绝。
    allOperation: |
      maxConcurrentCalls: 20
      maxWaitDuration: 1000

  http:
    dispatcher:
      edge:
        ## 后端服务
        url:
          enabled: true
          pattern: "/api/(.*)"
          mappings:
            resource-server:
              prefixSegmentCount: 2
              path: "/api/resource/.*"
              microserviceName: resource-server
            authentication-server:
              prefixSegmentCount: 2
              path: "/api/authentication/.*"
              microserviceName: authentication-server
            admin-service:
              prefixSegmentCount: 2
              path: "/api/admin/.*"
              microserviceName: admin-service
        ## 前端服务
        http:
          enabled: true
          pattern: "/ui/(.*)"
          mappings:
            admin-website:
              prefixSegmentCount: 0
              path: "/ui/admin/.*"
              microserviceName: admin-website
