apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  namespace: default
  labels:
    name: zookeeper-app
spec:
  containers:
    - name: zookeeper-container
      image: swr.cn-north-4.myhuaweicloud.com/wmwei/zookeeper:3.9.2
      ports:
        - containerPort: 2181
