#
## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------
servicecomb:
  service:
    application: scb-fence
    name: authentication-server
    version: 0.0.1

  registry:
    zk:
      enabled: true
      connectString: 127.0.0.1:2181
  config:
    zk:
      enabled: true
      connectString: 127.0.0.1:2181

  rest:
    address: 0.0.0.0:9061
  # HTTP container url prefix, or ROOT
  http:
    dispatcher:
      rest:
        pattern: "/authentication/(.*)"

  authentication:
    token:
      expiresIn: 3600
      guestExpiresQuickly:
        expiresIn: 3

    github:
      clientId: 94300caee0725405fde1 # WARNING: change to your github client id
      clientSecret: b139dbc8fe8be9153f68049bfa8387dfde33f1c9 # WARNING: change to your github client secret

db:
  password: root # WARNING: please change password in production environment

GithubOAuthService:
  urls:
    - rest://github.com:443?sslEnabled=true

spring:
  datasource:
    url: ${db.url:jdbc:mysql://localhost/authentication_server_db}
    username: ${db.username:root}
    password: ${db.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
